<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Silya" ignored="0" name="Test" tests="3" failures="1" timestamp="12 Dec 2022 17:20:56 GMT" time="0.006" errors="0">
  <testcase name="logic2" time="0.0" classname="logic.Second_Logic"/>
  <testcase name="logic1" time="0.002" classname="logic.First_Logic">
    <failure type="java.lang.AssertionError" message="logic1 is failed">
      <![CDATA[java.lang.AssertionError: logic1 is failed
at logic.First_Logic.logic1(First_Logic.java:11)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- logic1 -->
  <testcase name="logic3" time="0.0" classname="logic.Third_Logic"/>
</testsuite> <!-- Test -->
